baseurl = "https://garco.ga"
title = "GARCO"
theme = ""
languageCode = "it-it"
# Enable comments by entering your Disqus shortname
disqusShortname = "http-garco-ga"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-124901497-2"
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination
canonifyURLs = true

[taxonomies]
category = "categories"

[params]
# Unmark to use post folder for images. Default is static folder.
#usepostimgfolder = true
  slogan = ""
  description = "Benvenuti sul mio primo blog, GARCO. Il nome nasce dall'unione del mio cognome e del mio nome, Garantini e Marco, nessun motivo particolare, mi piaceva come suonava. Qui mi piacerebbe parlare un po'di tutto, tecnologia, musica, viaggi, etc., aspetto consigli!" # meta description
  author = "MG"
  authorLink = "about/"
  bio = [
    ""
  ]
  copyright = [
    "&copy; 2018 Marco Garantini",
    "Leggi la [Privacy Policy](/privacy)",
  ]


  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below (it is also used in Gravatar for the bio).
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "marco.garantini@hotmail.com"

  # Nav links in the side bar


  [[menu.main]]
  name = "CHI SONO"
  url = "about/"
  weight = 1

  [[menu.main]]
  name = "CONTATTI"
  url = "contact/"
  weight = 2

  [params.social]
  facebook      = "https://www.facebook.com/marco.garantini"
  googleplus    = ""
  email         = "marco.garantini@hotmail.com"
  twitter       = ""
  linkedin      = ""
  stackoverflow = ""
  instagram     = "https://www.instagram.com/korka1313/"
  github        = "https://github.com/Korka13"
  pinterest     = ""
  rss           = false
